### ISSUE TITLE
Use ACS multiyear files for matching

### ISSUE THREAD

**Issue by jo-fleck** [jiaxitan/Property-Tax-Imputing#5]
Has more observations per county, i.e. would solve the problem of unidentified counties in ACS.

**Comment by jiaxitan** [comment]
The minimum number of households in an identified county for any year in the sample is 151, and this number is even higher for unidentified counties. If we use the counties matched from PUMA, this number goes to 132, but still significantly larger than 10.

 It means that we don’t have to worry about matching sample size. So we can stick to the single year ACS files for now.
